CREATE TABLE page_runs (
  url VARCHAR(76) NOT NULL,
  startedDateTime INTEGER NOT NULL,
  rank2017 INTEGER,
  cdn VARCHAR(50),
  reqTotal INTEGER,
  reqHtml INTEGER,
  reqJS INTEGER,
  reqCSS INTEGER,
  reqImg INTEGER,
  bytesTotal INTEGER,
  bytesHtml INTEGER,
  bytesJS INTEGER,
  bytesCSS INTEGER,
  bytesImg INTEGER,
  TTFB INTEGER,
  performanceScore FLOAT,
  firstContentfulPaint INTEGER,
  maxPotentialFirstInputDelay INTEGER,
  speedIndex INTEGER,
  firstMeaningfulPaint INTEGER,
  firstCPUIdle INTEGER,
  timeToInteractive INTEGER,
  PRIMARY KEY(url, startedDateTime)
);

